### ISSUE TITLE
Industry MFP estimates aren't working

### ISSUE THREAD

**Issue by nerdcha** [MattCowgill/getabs#8]
Something's gone weird with cat number [5260.0.55.002](http://www.abs.gov.au/AUSSTATS/abs@.nsf/DetailsPage/5260.0.55.0022017-18?OpenDocument), but I can't figure out what.

```
> mfp <- get_abs("5260.0.55.002")
Finding filenames for tables from ABS catalogue 5260.0.55.002
Error in get_abs_xml_metadata(cat_no = cat_no) : 
  Couldn't find an ABS time series with catalogue number 5260.0.55.002
```

**Comment by MattCowgill** [comment]
It’s because the ABS classifies those tables as “data cubes” rather than time series, despite the fact that they are, in fact, time series. The package can only fetch tables the ABS classifies as time series (because they’re in the XML time series directory and are formatted consistently). Not much I can do about this one, sorry!
